// Autogenerated file - DO NOT EDIT

#pragma once

#include "video.h"

extern void annoying_dog_1_png_data(void);
const struct sprite_proto annoying_dog_1_png_proto = {
    .width = 23,
    .height = 19,
    .stride = 12,
    .data_start = (uint16_t*)annoying_dog_1_png_data
};

extern void annoying_dog_2_png_data(void);
const struct sprite_proto annoying_dog_2_png_proto = {
    .width = 23,
    .height = 19,
    .stride = 12,
    .data_start = (uint16_t*)annoying_dog_2_png_data
};

