import re
import sys
from PIL import Image
from argparse import ArgumentParser

VIDEO_BIT_PORT = 'PORTD'
VIDEO_BIT_PIN = 7

def make_name(path: str):
     return re.sub(r"[\/\.,-]", "_", path)

def is_power_of_two(n):
    return n != 0 and (n & (n - 1)) == 0

def build_asm_helper(name, pixels, width, height, file):
    identifier = f'sprites_{name}_start'

    print(f'.global {identifier}\n{identifier}:', file=file)
    for y in range(height):
        print(f'; row {y}', file=file)

        for x in range(width):
            # clear or set bit depending on our pixel value
            command = 'sbi' if pixels[x, y] > 127 else 'cbi'
            print(f'    {command} _SFR_IO_ADDR({VIDEO_BIT_PORT}), {VIDEO_BIT_PIN}', file=file)

        print('    ret', file=file)

p = ArgumentParser()
p.add_argument('--input', type=str, required=True, action='append')
args = p.parse_args()

with open('generated-sprites.S', 'w') as file:
    print('; Autogenerated file - DO NOT EDIT\n', file=file)
    print('#include <avr/io.h>\n.text\n', file=file)

    for path in args.input:
        image = Image.open(path).convert("L")
        width, height = image.size

        if not is_power_of_two(width + 1):
            print('image height must be any power of 2 minus 1, i.e (3, 7, 15)', file=sys.stderr)
            exit(1)

        build_asm_helper(make_name(path), image.load(), width, height, file)
